### ISSUE TITLE
compile Error:Execution failed for task ':app:tinkerProcessDebugManifest'. > tinkerId is not set!!!

### ISSUE THREAD

**Issue by jp1017** [xinghongfei/Hello-Tinker#1]
> Error:Execution failed for task ':app:tinkerProcessDebugManifest'.
> tinkerId is not set!!!

**Comment by xinghongfei** [comment]
加入版本控制，并提交一次？

**Comment by jp1017** [comment]
需要　`gitSha`哈, :smile: 

`gradle` 和 `git` 玩的很６嘛，厉害了我的哥

**Comment by xinghongfei** [comment]
这个坑我也踩过
